
services:

  mysql2:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql2
    volumes:
      - .:/home/app

volumes:
  mysql_data: